{{- if .Values.app.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mantis.fullname" . }}-attachments
  labels:
    {{- include "mantis.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.app.attachments.storage }}
  {{- with .Values.app.attachments.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
