{{- if and .Values.app.enabled (eq (.Values.runtime.mode | default "dind") "dind") .Values.runtime.dind.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mantis.fullname" . }}-dind-storage
  labels:
    {{- include "mantis.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.runtime.dind.storage.size }}
  {{- with .Values.runtime.dind.storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
