{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ include "mantis.namespace" . }}
  labels:
    app: mantis-frontend
    {{- include "mantis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: mantis-frontend
{{- end }}
