{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: {{ include "mantis.namespace" . }}
  labels:
    {{- include "mantis.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
  {{- if .Values.postgres.storageClassName }}
  storageClassName: {{ .Values.postgres.storageClassName | quote }}
  {{- end }}
{{- end }}
