{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "mantis.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "mantis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
