{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ include "mantis.namespace" . }}
  labels:
    app: postgres
    {{- include "mantis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
      name: postgres
  selector:
    app: postgres
{{- end }}
