apiVersion: v1
kind: Secret
metadata:
  name: mantis-secrets
  namespace: {{ include "mantis.namespace" . }}
  labels:
    {{- include "mantis.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-user: {{ .Values.secrets.postgres.user | quote }}
  postgres-password: {{ .Values.secrets.postgres.password | quote }}
  postgres-db: {{ .Values.secrets.postgres.db | quote }}
